name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.3.0
        with:
          title-regex: "^(PPMPLPR-\\d+:|hotfix).+"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "PR title is invalid"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@v1.2.0
        with:
          valid-labels: 'bug, feature, refactor, docs'
          github-token: '${{ secrets.GITHUB_TOKEN }}'